package routes

import (
	"siakad-backend/controllers/kencana"
	"siakad-backend/middleware"

	"github.com/gofiber/fiber/v2"
)

func SetupKencanaRoutes(app *fiber.App) {
	api := app.Group("/api", middleware.AuthProtected)

	student := api.Group("/kencana-student", middleware.MahasiswaCheck)
	student.Get("/dashboard", kencana.GetDashboard)
	student.Get("/mentor-invitations", kencana.GetMentorInvitations)
	student.Post("/mentor-invitations/:id/respond", kencana.RespondMentorInvitation)
	student.Get("/timeline", kencana.GetTimeline)
	student.Get("/stages/:stageId", kencana.GetStage)
	student.Get("/sessions/:sessionId", kencana.GetSession)
	student.Post("/materials/:materialId/complete", kencana.CompleteMaterial)
	student.Get("/quizzes/:quizId", kencana.GetQuiz)
	student.Post("/quizzes/:quizId/start", kencana.StartQuiz)
	student.Post("/quiz-attempts/:attemptId/answers", kencana.SaveQuizAnswer)
	student.Post("/quiz-attempts/:attemptId/submit", kencana.SubmitQuizAttempt)
	student.Get("/assignments/:assignmentId", kencana.GetAssignment)
	student.Post("/assignments/:assignmentId/submit", kencana.SubmitAssignment)
	student.Get("/handbook", kencana.GetHandbook)
	student.Post("/handbook/draft", kencana.SaveHandbookDraft)
	student.Post("/handbook/submit", kencana.SubmitHandbook)
	student.Get("/attendance", kencana.GetAttendance)
	student.Get("/score", kencana.GetScore)
	student.Get("/remedial", kencana.GetRemedial)
	student.Get("/certificate", kencana.GetCertificate)

	admin := api.Group("/kencana-admin", middleware.KencanaAdminCheck)
	admin.Get("/periods", kencana.ListPeriods)
	admin.Post("/periods", kencana.CreatePeriod)
	admin.Put("/periods/:id", kencana.UpdatePeriod)
	admin.Get("/stages", kencana.ListStages)
	admin.Post("/stages", kencana.CreateStage)
	admin.Put("/stages/:id", kencana.UpdateStage)
	admin.Get("/sessions", kencana.ListSessions)
	admin.Post("/sessions", kencana.CreateSession)
	admin.Put("/sessions/:id", kencana.UpdateSession)
	admin.Post("/materials", kencana.CreateMaterial)
	admin.Post("/quizzes", kencana.CreateQuiz)
	admin.Get("/quizzes/:id", kencana.GetQuizDetail)
	admin.Post("/questions", kencana.CreateQuestion)
	admin.Put("/questions/:id", kencana.UpdateQuestion)
	admin.Post("/assignments", kencana.CreateAssignment)
	admin.Get("/participants", kencana.ListParticipants)
	admin.Get("/scores", kencana.ListScores)
	admin.Post("/remedials", kencana.CreateRemedial)
	admin.Post("/certificates/generate", kencana.GenerateCertificate)
	admin.Get("/mentors", kencana.ListMentors)
	admin.Post("/mentors", kencana.CreateMentor)
	admin.Put("/mentors/:id", kencana.UpdateMentor)
	admin.Delete("/mentors/:id", kencana.DeleteMentor)
	admin.Get("/mentor-assignments", kencana.ListMentorAssignments)
	admin.Post("/mentor-assignments", kencana.CreateMentorAssignment)
	admin.Put("/mentor-assignments/:id/move", kencana.MoveMentorAssignment)
	admin.Delete("/mentor-assignments/:id", kencana.DeleteMentorAssignment)

	fakultas := api.Group("/kencana-fakultas", middleware.KencanaFakultasCheck)
	fakultas.Get("/participants", kencana.ListParticipants)
	fakultas.Get("/scores", kencana.ListScores)
	fakultas.Get("/stages", kencana.ListStages)
	fakultas.Get("/mentors", kencana.ListMentors)
	fakultas.Post("/mentors", kencana.CreateMentor)
	fakultas.Put("/mentors/:id", kencana.UpdateMentor)
	fakultas.Delete("/mentors/:id", kencana.DeleteMentor)

	mentor := api.Group("/kencana-mentor", middleware.KencanaMentorCheck)
	mentor.Get("/dashboard", kencana.MentorDashboard)
	mentor.Get("/profile", kencana.MentorProfile)
	mentor.Put("/profile", kencana.UpdateMentorProfile)
	mentor.Get("/available-students", kencana.MentorAvailableStudents)
	mentor.Get("/students", kencana.MentorStudents)
	mentor.Post("/invitations", kencana.MentorInviteStudents)
	mentor.Delete("/assignments/:id", kencana.MentorRemoveAssignment)
	mentor.Get("/students/:studentId/progress", kencana.MentorStudentProgress)
	mentor.Get("/students/:studentId/score", kencana.MentorStudentScore)
	mentor.Get("/students/:studentId/attendance", kencana.MentorStudentAttendance)
	mentor.Get("/students/:studentId/handbook", kencana.MentorStudentHandbook)
	mentor.Post("/students/:studentId/notes", kencana.MentorCreateNote)
	mentor.Post("/students/:studentId/score-items", kencana.MentorCreateScoreItem)
}
