package routes

import (
	"siakad-backend/controllers"
	"siakad-backend/controllers/kencana"
	"siakad-backend/middleware"

	"github.com/gofiber/fiber/v2"
)

func SetupKencanaRoutes(app *fiber.App) {
	api := app.Group("/api", middleware.AuthProtected)

	student := api.Group("/kencana-student", middleware.MahasiswaCheck)
	student.Get("/dashboard", kencana.GetDashboard)
	student.Get("/mentor-invitations", kencana.GetMentorInvitations)
	student.Post("/mentor-invitations/:id/respond", kencana.RespondMentorInvitation)
	student.Post("/group-invitations/:id/respond", kencana.RespondGroupInvitation)
	student.Get("/timeline", kencana.GetTimeline)
	student.Get("/stages/:stageId", kencana.GetStage)
	student.Get("/sessions/:sessionId", kencana.GetSession)
	student.Post("/materials/:materialId/complete", kencana.CompleteMaterial)
	student.Get("/quizzes/:quizId", kencana.GetQuiz)
	student.Post("/quizzes/:quizId/start", kencana.StartQuiz)
	student.Post("/quiz-attempts/:attemptId/answers", kencana.SaveQuizAnswer)
	student.Post("/quiz-attempts/:attemptId/submit", kencana.SubmitQuizAttempt)
	student.Get("/assignments/:assignmentId", kencana.GetAssignment)
	student.Post("/assignments/:assignmentId/submit", kencana.SubmitAssignment)
	student.Get("/handbook", kencana.GetHandbook)
	student.Post("/handbook/draft", kencana.SaveHandbookDraft)
	student.Post("/handbook/submit", kencana.SubmitHandbook)
	student.Get("/attendance", kencana.GetAttendance)
	student.Get("/score", kencana.GetScore)
	student.Get("/remedial", kencana.GetRemedial)
	student.Get("/certificate", kencana.GetCertificate)

	admin := api.Group("/kencana-admin", middleware.KencanaAdminCheck)
	admin.Get("/faculties", controllers.GetAllFakultas)
	admin.Get("/majors", controllers.GetAllProgramStudi)
	// Periods
	admin.Get("/periods", kencana.ListPeriods)
	admin.Post("/periods", kencana.CreatePeriod)
	admin.Put("/periods/:id", kencana.UpdatePeriod)
	admin.Get("/periods/:id/phases", kencana.GetPeriodPhases)
	admin.Put("/periods/:id/timeline/:phaseType", kencana.UpdateTimelinePhase)
	admin.Post("/periods/:id/university/:action", kencana.UpdateUniversityPhase)
	admin.Post("/periods/:id/faculty/open", kencana.OpenFacultyPhases)
	// Media Upload
	admin.Post("/upload", kencana.UploadMedia)
	// Stages
	admin.Get("/stages", kencana.ListStages)
	admin.Post("/stages", kencana.CreateStage)
	admin.Put("/stages/:id", kencana.UpdateStage)
	// Sessions
	admin.Get("/sessions", kencana.ListSessions)
	admin.Get("/sessions/:id", kencana.GetAdminSessionDetail)
	admin.Post("/sessions", kencana.CreateSession)
	admin.Put("/sessions/:id", kencana.UpdateSession)
	// Materials (CRUD + file upload)
	admin.Post("/materials", kencana.CreateMaterial)
	admin.Put("/materials/:id", kencana.UpdateMaterial)
	admin.Delete("/materials/:id", kencana.DeleteMaterial)
	admin.Post("/materials/upload", kencana.UploadMaterial)
	// Quizzes & Questions
	admin.Post("/quizzes", kencana.CreateQuiz)
	admin.Put("/quizzes/:id", kencana.UpdateQuiz)
	admin.Delete("/quizzes/:id", kencana.DeleteQuiz)
	admin.Get("/quizzes/:id", kencana.GetQuizDetail)
	admin.Post("/questions", kencana.CreateQuestion)
	admin.Put("/questions/:id", kencana.UpdateQuestion)
	// Assignments (CRUD)
	admin.Post("/assignments", kencana.CreateAssignment)
	admin.Put("/assignments/:id", kencana.UpdateAssignment)
	admin.Delete("/assignments/:id", kencana.DeleteAssignment)
	// Participants & Scores
	admin.Get("/participants", kencana.ListParticipants)
	admin.Get("/scores", kencana.ListScores)
	admin.Get("/score-items", kencana.AdminListScoreItems)
	admin.Post("/score-items", kencana.UpsertScoreItem)
	admin.Post("/score-items/bulk", kencana.BulkUpsertScoreItems)
	admin.Get("/scores/summary", kencana.ScoreSummary)
	admin.Post("/scores/calculate", kencana.CalculateAllScores)
	// Remedials & Certificates
	admin.Get("/remedials", kencana.ListRemedials)
	admin.Post("/remedials", kencana.CreateRemedial)
	admin.Get("/certificates", kencana.ListCertificates)
	admin.Post("/certificates/generate", kencana.GenerateCertificate)
	// Mentors
	admin.Get("/mentors", kencana.ListMentors)
	admin.Post("/mentors", kencana.CreateMentor)
	admin.Put("/mentors/:id", kencana.UpdateMentor)
	admin.Delete("/mentors/:id", kencana.DeleteMentor)
	admin.Get("/mentor-assignments", kencana.ListMentorAssignments)
	admin.Post("/mentor-assignments", kencana.CreateMentorAssignment)
	admin.Put("/mentor-assignments/:id/move", kencana.MoveMentorAssignment)
	admin.Delete("/mentor-assignments/:id", kencana.DeleteMentorAssignment)
	// Groups
	admin.Get("/groups", kencana.ListGroups)
	admin.Post("/groups", kencana.CreateGroup)
	admin.Post("/groups/auto-assign", kencana.AutoAssignGroups)
	admin.Get("/groups/:id", kencana.GetGroup)
	admin.Put("/groups/:id", kencana.UpdateGroup)
	admin.Delete("/groups/:id", kencana.DeleteGroup)
	admin.Post("/groups/:id/members", kencana.AddGroupMembers)
	admin.Delete("/groups/:id/members/:studentId", kencana.RemoveGroupMember)

	fakultas := api.Group("/kencana-fakultas", middleware.KencanaFakultasCheck)
	fakultas.Get("/participants", kencana.ListParticipants)
	fakultas.Get("/scores", kencana.ListScores)
	fakultas.Get("/remedials", kencana.ListRemedials)
	fakultas.Get("/certificates", kencana.ListCertificates)
	fakultas.Get("/phase", kencana.GetFacultyPhase)
	fakultas.Put("/phase", kencana.UpdateFacultyPhase)
	fakultas.Post("/phase/start", kencana.StartFacultyPhase)
	fakultas.Post("/phase/complete", kencana.CompleteFacultyPhase)
	fakultas.Get("/stages", kencana.ListStages)
	fakultas.Post("/stages", kencana.CreateStage)
	fakultas.Put("/stages/:id", kencana.UpdateStage)
	fakultas.Get("/sessions", kencana.ListSessions)
	fakultas.Get("/sessions/:id", kencana.GetAdminSessionDetail)
	fakultas.Post("/sessions", kencana.CreateSession)
	fakultas.Put("/sessions/:id", kencana.UpdateSession)
	fakultas.Get("/mentors", kencana.ListMentors)
	fakultas.Post("/mentors", kencana.CreateMentor)
	fakultas.Put("/mentors/:id", kencana.UpdateMentor)
	fakultas.Delete("/mentors/:id", kencana.DeleteMentor)
	fakultas.Get("/groups", kencana.ListGroups)
	fakultas.Post("/groups", kencana.CreateGroup)
	fakultas.Post("/groups/auto-assign", kencana.AutoAssignGroups)
	fakultas.Get("/groups/:id", kencana.GetGroup)
	fakultas.Put("/groups/:id", kencana.UpdateGroup)
	fakultas.Delete("/groups/:id", kencana.DeleteGroup)
	fakultas.Post("/groups/:id/members", kencana.AddGroupMembers)
	fakultas.Delete("/groups/:id/members/:studentId", kencana.RemoveGroupMember)

	mentor := api.Group("/kencana-mentor", middleware.KencanaMentorCheck)
	mentor.Get("/dashboard", kencana.MentorDashboard)
	mentor.Get("/profile", kencana.MentorProfile)
	mentor.Put("/profile", kencana.UpdateMentorProfile)
	mentor.Get("/available-students", kencana.MentorAvailableStudents)
	mentor.Get("/students", kencana.MentorStudents)
	mentor.Post("/invitations", kencana.MentorInviteStudents)
	mentor.Delete("/assignments/:id", kencana.MentorRemoveAssignment)
	mentor.Get("/students/:studentId/progress", kencana.MentorStudentProgress)
	mentor.Get("/students/:studentId/score", kencana.MentorStudentScore)
	mentor.Get("/students/:studentId/attendance", kencana.MentorStudentAttendance)
	mentor.Get("/students/:studentId/handbook", kencana.MentorStudentHandbook)
	mentor.Post("/students/:studentId/notes", kencana.MentorCreateNote)
	mentor.Post("/students/:studentId/score-items", kencana.MentorCreateScoreItem)
	mentor.Put("/students/:studentId/score-items", kencana.MentorUpsertBulkScoreItems)
	mentor.Post("/students/:studentId/handbook/review", kencana.MentorReviewHandbook)
	mentor.Get("/groups", kencana.MentorListGroups)
	mentor.Get("/groups/:id", kencana.MentorGetGroup)
	mentor.Post("/groups/:id/members", kencana.MentorAddGroupMembers)
	mentor.Delete("/groups/:id/members/:studentId", kencana.MentorRemoveGroupMember)
}
